version: '3'
services:
  local_operations:
    environment:
      - USER_INDEX=0
      - TO_CONNECT=1
      - GROUP_SIZE=4
    restart: always
    build: application
    networks:
      - default
    ports:
      - '9050:9050'
    volumes:
      - type: bind
        source: ./cifar-10-batches-py
        target: /cifar-10-batches-py

networks:
  default:
    driver: bridge
    name: custom_fl
