version: '3'
services:
  local_operations:
    environment:
      - USER_INDEX=1
    restart: always
    container_name: local_operations
    build: application
    networks:
      - default
    ports:
      - "9050:9050"
    depends_on:
      - db
    volumes:
      - type: bind
        source: \\wsl.localhost\Ubuntu20.04LTS\home\new\leaf\data\femnist\data
        target: /data
  db:
    container_name: db
    restart: always
    image: mongo:latest
    networks:
      - default
    ports:
      - 27017:27017

networks:
  default:
    driver: bridge
    name: custom_fl