version: '3'
services:
  local_operations:
    environment:
      - USER_INDEX=${USER_INDEX}
      - TO_CONNECT=${TO_CONNECT_INDEX}
    restart: always
    build: application
    networks:
      - default
    ports:
      - '905${USER_INDEX}:9050'
    volumes:
      - type: bind
        source: /Users/karolinabogacka/PycharmProjects/fl-local-operations/cifar-10-batches-py
        target: /cifar-10-batches-py

networks:
  default:
    driver: bridge
    name: custom_fl
