version: '3'
services:
  local_operations:
    environment:
      - USER_INDEX=3
    restart: always
    build: application
    networks:
      - default
    ports:
      - '9053:9050'
    #volumes:
    #  - type: bind
    #    source: \\wsl.localhost\Ubuntu20.04LTS\home\new\leaf\data\femnist\data
    #    target: /data
    volumes:
      - type: bind
        source: /mnt/c/Users/kboga/PycharmProjects/localOperationsBeta/data
        target: /data

networks:
  default:
    driver: bridge
    name: custom_fl