version: '3'
services:
  local_operations:
    environment:
      - USER_INDEX=5
      - GROUP_INDEX=1
    restart: always
    build: application
    networks:
      - default
    ports:
      - '905${USER_INDEX}:9050'
      #- '8082:8082'
    #volumes:
    #  - type: bind
    #    source: \\wsl.localhost\Ubuntu20.04LTS\home\new\leaf\data\femnist\data
    #    target: /data
    volumes:
      - type: bind
        source: /home/wasielk/federated-experiments/fl-local-operations/cifar-10-batches-py
        target: /cifar-10-batches-py

networks:
  default:
    driver: bridge
    name: custom_fl
