version: '3'
services:
  local_operations:
    environment:
      - USER_INDEX=7
      - TO_CONNECT=4
      - GROUP_SIZE=4
    restart: always
    build: application
    networks:
      - default
    ports:
      - '9057:9050'
    volumes:
      - type: bind
        source: /home/rsa-key-20220518/local-operations/german-traffic
        target: /german-traffic

networks:
  default:
    driver: bridge
    name: custom_fl
